[package]
name = "sc2-macro"
version = "1.0.0"
edition = "2024"
description = "Procedural macros for rust-sc2 API"
readme = "../README.md"

[dependencies]
sc2-proc-macro = { path = "../macro", version = "1" }
